### ISSUE TITLE
How to use skip function? also some async error

### ISSUE THREAD

**Issue by Melkznav** [ZhenShuo2021/V2PH-Downloader#4]
**Summary**  
I face a problem like not functioning skip function and error that doesn't allow me to download

**Details**  
This is for the skip function:
C:\Users\Administrator>v2dl "https://www.v2ph.com/album/z7xn5x4a.html"
[10:57:40][info] - Permissions updated for folder at C:\Users\Administrator\AppData\Roaming\v2dl\.keys
[10:57:40][info] - Key pair already exists
[10:57:40][info] - Master key decryption successful
[10:57:40][info] - Keys loaded and validated successfully
[10:57:40][info] - Album https://www.v2ph.com/album/z7xn5x4a.html?hl=ja already downloaded, skipping.
[10:57:40][info] - Download finished, showing download status

C:\Users\Administrator>v2dl "https://www.v2ph.com/album/z7xn5x4a.html" --no-skip
usage: v2dl [-h] [-i PATH] [-a] [-b {selenium,drissionpage}] [-c PATH] [-d PATH] [-D PATH] [-f] [-l LANG]
            [--range RANGE] [--no-metadata] [--metadata-path PATH] [--max-worker N] [--min-scroll N] [--max-scroll N]
            [--chrome-args '--arg1//--arg2'] [--user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)...'] [--dry-run]
            [--terminate] [--use-default-chrome-profile] [-V] [-q | -v | --log-level {1,2,3,4,5}]
            [url]
v2dl: error: unrecognized arguments: --no-skip

and this is for the async error i said earlier:
C:\Users\Administrator>v2dl "https://www.v2ph.com/album/z7xn5x4a.html"
[10:47:45][info] - Permissions updated for folder at C:\Users\Administrator\AppData\Roaming\v2dl\.keys
[10:47:45][info] - Key pair already exists
[10:47:45][info] - Master key decryption successful
[10:47:45][info] - Keys loaded and validated successfully
[10:47:45][info] - Starting to scrape album links from https://www.v2ph.com/album/z7xn5x4a.html?hl=ja
[10:47:58][info] - Fetching content from https://www.v2ph.com/album/z7xn5x4a.html?hl=ja&page=1
[10:47:58][info] - Found 10 images on page 1
[10:48:02][error] - Error in async task 'https://cdn.v2ph.com/photos/AHSKnT2Svsm8luJm.jpg':
[10:48:02][error] - Error in async task 'https://cdn.v2ph.com/photos/0HqL4sALAqU0omaB.jpg':
[10:48:02][error] - Error in async task 'https://cdn.v2ph.com/photos/VaPeVMWXkE6PN42Z.jpg':
[10:48:04][error] - Error in async task 'https://cdn.v2ph.com/photos/ZF8mLXB47SAIZJzK.jpg':
[10:48:04][error] - Error in async task 'https://cdn.v2ph.com/photos/0QUEvgvt9fyJ8diH.jpg':
[10:48:05][error] - Error in async task 'https://cdn.v2ph.com/photos/3JwbwqkMuAVC7l6p.jpg':
[10:48:05][error] - Error in async task 'https://cdn.v2ph.com/photos/C6ZM_1MlwRu5RstG.jpg':
[10:48:05][error] - Error in async task 'https://cdn.v2ph.com/photos/XvKFrc461d3nWg1p.jpg':
[10:48:05][error] - Error in async task 'https://cdn.v2ph.com/photos/I16OcEQ2A9f5Lbq6.jpg':
[10:48:06][info] - Downloaded: 'C:\Users\Administrator\Downloads\[XiuRen秀人网] No.9998 白浅浅 丝袜美腿\001'

The reason i've tried the no skip function is because of these async error.
I am thankful for the tools you've given to this world sir.

**Comment by ZhenShuo2021** [comment]
Appreciate the feedback! The new release is now available.

1. `--no-skip` has been replaced with `--force`, and the docs are updated.
2. The async error has been fixed.

Feel free to let me know if you run into any other issues!

**Comment by Melkznav** [comment]
Hi idk why but im still facing some async error. Some files did get downloaded but some not. So the album have some blanks like pic 1, pic 2, pic 4. where pic 3 had error and didn't get downloaded. 

Edit 1:
Also i try to use the --chrome-args but it doesn't work:
C:\Users\Administrator>v2dl "https://www.v2ph.com/actor/Maleah" --force --crhome-args
usage: v2dl [-h] [-i PATH] [-a] [-b {selenium,drissionpage}] [-c PATH] [-d PATH] [-D PATH] [-f] [-l LANG]
            [--range RANGE] [--no-metadata] [--metadata-path PATH] [--max-worker N] [--min-scroll N] [--max-scroll N]
            [--chrome-args '--arg1//--arg2'] [--user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)...'] [--dry-run]
            [--terminate] [--use-default-chrome-profile] [-V] [-q | -v | --log-level {1,2,3,4,5}]
            [url]
v2dl: error: unrecognized arguments: --crhome-args

I tried this because i thought that maybe this error async is because of bot blocked scenario.

Edit 2:
How about a feature that ignores already downloaded pictures and only target the not downloaded ones. Also is there a place where the software stores history? cause i want to wipe it clean if possible. to not need to use the --force function

**Comment by ZhenShuo2021** [comment]
Hey, thanks for your feedback.

1. **Missing images / async error**  
   I couldn’t reproduce the issue on my side. I’ve also tried making some changes, please update to the latest version and check if the issue persists.

2. **`--chrome-args` not working**  
   Looks like there was just a typo in your command (`--crhome-args` instead of `--chrome-args`). Furthermore, the example usage is in the README now.

3. **Skip already downloaded images & reset history**  
   It's described in README:  
   ```
   C:\Users\xxx\AppData\Roaming\v2dl
   ```

Let me know if you run into anything else.

**Comment by Melkznav** [comment]
Hello sorry for the late reply. How do i update to get the 0.4.0? also do i need to download it? how to delete the original v2dl? cause when i try the basic command "pip install v2dl" it keep saying already satisfied. But when i try to download something it gave this instead :

C:\Users\Administrator>v2dl "https://www.v2ph.com/album/XIUREN-8072"
<coroutine object main at 0x00000257661FA330>
<sys>:0: RuntimeWarning: coroutine 'main' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Thanks for your previous reply. i shall wait your response. Sorry that i am too lack of knowledge in these things.

**Comment by ZhenShuo2021** [comment]
Thanks for your report! A new version has been released, and the bugs are being fixed.

Don't worry about those common issues for non-developers. V2DL is a Python package, and pip is the package manager in Python. Here are some pip guides:

- To upgrade a package, simply use the `-U` flag (--upgrade), e.g., `pip install -U v2dl` or specify a version with `pip install v2dl==0.4.2`.
- To remove all packages, use `pip freeze > unins && pip uninstall -y -r unins && rm unins`.
- To check the installed packages, use `pip list`.
- Many CLI tools have a `version` or `--version` flag, just like v2dl.

**Comment by Melkznav** [comment]
Hi thanks now i can download everything. But i encounter another problem.

C:\Users\Administrator>v2dl "https://www.v2ph.com/album/z6me9ema.html" --force
[19:27:56][info] - Permissions updated for folder at C:\Users\Administrator\AppData\Roaming\v2dl\.keys
[19:27:56][info] - Key pair already exists
[19:27:56][info] - Master key decryption successful
[19:27:56][info] - Keys loaded and validated successfully
[19:27:57][info] - Starting to scrape image links from https://www.v2ph.com/album/z6me9ema.html?hl=ja
[19:28:10][info] - Fetching content from https://www.v2ph.com/album/z6me9ema.html?hl=ja&page=1
[19:28:15][error] - Error downloading 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキン グ美脚\007':
[19:28:15][error] - Error downloading 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキン グ美脚\006':
[19:28:15][error] - Error downloading 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキン グ美脚\005':
[19:28:15][error] - Error downloading 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキン グ美脚\009':
[19:28:15][error] - Error downloading 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキン グ美脚\001':
[19:28:17][info] - Downloaded: 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキング美脚\008.jpg'
[19:28:17][info] - Downloaded: 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキング美脚\004.jpg'
[19:28:17][info] - Downloaded: 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキング美脚\010.jpg'
[19:28:17][info] - Downloaded: 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキング美脚\002.jpg'
[19:28:17][info] - Downloaded: 'C:\Users\Administrator\Downloads\[秀人] No.9860 キャンディ・タンタンのストッキング美脚\003.jpg'
[19:28:17][warning] - Failed to download 5 images
 before i can download everything fine. i think this issue could be because im using phone hotspot cause before i use wifi.
Also how do i only download the files that failed to be downloaded?

**Comment by ZhenShuo2021** [comment]
Use range flag: `v2dl "https://www.v2ph.com/album/z6me9ema.html" -f --range 1`. You can use `--range 2-4` to download page 2 to 4.
